security:
  enable_authenticator_manager: true

  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    user:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    docs:
      pattern: ^/api/docs
      security: false

    login:
      pattern: ^/api/auth/login
      stateless: true
      json_login:
        check_path: /api/auth/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api_token_refresh:
      pattern: ^/api/auth/refresh
      stateless: true
      refresh_jwt: ~

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

  access_control:
    - { path: ^/api/auth/refresh, roles: PUBLIC_ACCESS }
    - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/, roles: [ 'ROLE_USER' ] }
